baithi/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from inside import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'inside/', include('inside.urls')),
    path(r'cart/', include('cart.urls')),
    path(r'social-auth/', include('social_django.urls', namespace="social")),
    path(r'orders/', include('orders.urls')),
    path(r'accounts/', include('allauth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

inside/urls.py
from django.conf.urls import url
from inside import views
from django.urls import path

app_name = 'inside'

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'signin', views.signin, name = 'signin'),
    url(r'signup', views.signup, name = 'signup'),
    url(r'logout', views.user_logout, name = 'logout'),
    url(r'chi-tiet/(\d+)$', views.chiTiet,name='chi-tiet'),
    url(r'registered', views.Registration,name='registered'),
    path('user_change_password', views.user_change_password, name='user_change_password'),
    path('profile', views.user_profile, name='profile'),
    path('user_update', views.user_update, name='user_update'),
    
]

urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from inside import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'inside/', include('inside.urls')),
    path(r'cart/', include('cart.urls')),
    path(r'social-auth/', include('social_django.urls', namespace="social")),
    path(r'orders/', include('orders.urls')),
    path(r'accounts/', include('allauth.urls')),
    path(r'booking/', include('bookingsite.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inside/models.py
from django.db import models
from django.contrib.auth.models import User as UserAdmin
from django.contrib.auth.models import User
from django.forms import ModelForm
# Create your models here.

class SanPham(models.Model):
    id=models.AutoField(primary_key=True)
    ten_san_pham=models.CharField('Ten san pham', max_length=200, unique=True)
    hinh = models.ImageField('Hinh', upload_to='hinh_san_pham', blank=True)
    don_gia_ban = models.FloatField('Don gia')
    mo_ta_tom_tat = models.CharField('Tom tat', max_length=200)
    chi_tiet = models.TextField('Chi tiet')
    trang_thai = models.BooleanField('Trang thai',blank=True, default=True)
    def __str__(self):
        return self.ten_san_pham


class UserProfileInfo(models.Model):
    user= models.OneToOneField(User,on_delete=models.CASCADE)
    #additional
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    portfolio_site = models.URLField(blank = True)

    profile_pic = models.ImageField(upload_to = "profile_pics",blank = True)
    def __str__(self):
        return self.user.username
        
class Comment(models.Model):
    STATUS = (
        ('New', 'New'),
        ('True','True'),
        ('False','False'),
    )
    product = models.ForeignKey(SanPham, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    subject = models.CharField(max_length=50, blank=True)
    comment = models.CharField(max_length=250, blank=True)
    rate = models.IntegerField(default = 1)
    ip = models.CharField(max_length=20, blank = True)
    status = models.CharField(max_length=10, choices=STATUS, default= 'New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment', 'rate']

inside/forms.py
from django import forms
from inside.models import User
from .models import UserProfileInfo
from django.contrib.auth.models import User as UserAdmin
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import TextInput

class FormRegister(forms.ModelForm):
    name = forms.CharField(label='Your name', max_length=100)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    confirm = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['name', 'email', 'password']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = UserAdmin
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('first_name','last_name','portfolio_site','profile_pic')

class UserUpdateForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = ('first_name', 'last_name','email',)
        widgets = {
            'first_name': TextInput(attrs={'class': 'input', 'placeholder': 'First Name','help_text':'Optional.'}),
            'last_name' : TextInput(attrs={'class': 'input','placeholder':'Last Name','help_text':'Optional.'}),
            'email'     : TextInput(attrs={'class': 'input','placeholder':'Email', 'help_text':'Required. Inform a valid email address.'}),
            'username'  : TextInput(attrs={'class': 'input','placeholder':'Username'}),
        }

inside/views.py
from django.shortcuts import render
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from inside.models import SanPham
from datetime import datetime
from inside.models import User
from . import forms
from cart.forms import CartAddProductForm
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib import messages
from django.db import models
from inside.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login,update_session_auth_hash, logout
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from django.contrib.auth.decorators import login_required
from . import models
from inside import forms
from .forms import UserUpdateForm
# Create your views here.
def index(request):
    SanPham_list = SanPham.objects.all()
    num_visits = request.session.get('num_visits',0)
    request.session['num_visits'] = num_visits+1

    response = render(request, "inside/index.html", {'sanpham_list':SanPham_list, 'num_visits':num_visits})
    date1 = datetime.now()
    response.set_cookie("last_visit", date1.strftime('%d-%m-%Y %H:%M:%S'))
    last_visit = request.COOKIES.get('last_visit')

    return render(request, "inside/index.html", {'sanpham_list':SanPham_list, 'num_visits':num_visits, 'last_visit': last_visit})

def index1(request):
    return render(request,'basic_app/index.html')

def signin(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'inside/signin.html', {})

@login_required(login_url='/login')
def user_logout(request):
    logout(request)
    result = "You have logged out, Please choose  SIGN IN"

    return render(request, "inside/logout.html", {"result":result})

@login_required(login_url='/login')
def signup(request):
    form = forms.FormRegister()
    if request.method == 'POST':
        form =forms.FormRegister(request.POST, User)

        if form.is_valid() and form.cleaned_data['password'] == form.cleaned_data['confirm']:
            request.POST._mutable = True
            post = form.save(commit = False)
            post.name = form.cleaned_data['name']
            post.email = form.cleaned_data['email']
            post.password = form.cleaned_data['password']
            post.save()
            print("Saved to database")

        elif form.cleaned_data['password'] != form.cleaned_data['confirm']:
            form.add_error('confirm', 'The password does not match')
            print("Not confirm!")
    return render(request, "inside/signup.html", {'form': form})

def chiTiet(request, id):
    sanPham = SanPham.objects.get(id=id)
    cart_product_form = CartAddProductForm()
    return render(request,'inside/chitiet.html',{'sanPham':sanPham, 'cart_product_form': cart_product_form})


@login_required(login_url='/login')
def user_update(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'Your Profile was successfully updated!')
            return HttpResponseRedirect('profile')
    else:
        form = UserUpdateForm(instance=request.user)
    context = {'page': 'user',
               'form': form,
              }
    return render(request, "inside/user_update.html", context)

@login_required
def user_change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return HttpResponseRedirect('user_change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    context = {'page': 'user',
               'form':form,
               }
    return render(request, "inside/user_change_password.html",context)


@login_required(login_url='/login')
def user_profile(request):
    context = {'page': 'user',}
    return render(request, "inside/user_detail.html", context)

def Registration(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data= request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user =user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'inside/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registerd': registered})

templates/inside/chitiet.html
{% load static %}
<!doctype html>
<html lang="en">

<head>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Details</title>

    <!-- Custom fonts for this theme -->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="assets/ico/favicon.ico">

    <!-- Theme CSS -->
    <link href="{% static 'css_js' %}/css/freelancer.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300">
    <link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
    <link href="http://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">

</head>

<body>

    <!-- Header -->

    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">ORDER</a>
            <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'inside:index' %}">Products</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'inside:index' %}">About</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'inside:index' %}">Contact</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'inside:signin' %}">Sign in</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'inside:signup' %}">Sign up</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- End Header -->

    <!-- Begin #services-section -->
    <span style="display:inline-block; width: 500;"></span>
    <section class="page-section portfolio" id="portfolio">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <img width="240" height="260" src="{{sanPham.hinh.url}}" />
                </div>
                <div class="post_text form-inline">
                    <p class="services-body">Description: {{sanPham.chi_tiet}}</p>
                    <p class="services-body">Products on store: {{sanPham.trang_thai}}</p>
                </div>
                <form action="{% url 'cart:cart_add' sanPham.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-inline">
                        <label>
                            <input type = "radio" name = "Th_don_gia" value = "{{sanPham.don_gia_ban}}" checked /> Price: {{sanPham.don_gia_ban}} VND
                        </label>
                    </div>
                    <div class="post_text form-inline">

                        {{cart_product_form.quantity}}
                        <input type="submit" value="Add to cart" class="btn btn-success" style="margin-left:10px">
                    </div>
                </form>
            </div>
        </div>
    </section>
    <!-- End #services-section -->

    <div class="container">
      <div class="row">
        <div class="col-md-8 card mb-4  mt-3 left  top">
          <div class="card-body">
            <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
            <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
            <p class="card-text ">{{ post.content | safe }}</p>
          </div>
        </div>
    
        <div class="col-md-8 card mb-4  mt-3 ">
          <div class="card-body">
            <!-- comments -->
            <h2>{{ comments.count }} comments</h2>
    
            {% for comment in comments %}
            <div class="comments" style="padding: 10px;">
              <p class="font-weight-bold">
                {{ comment.name }}
                <span class=" text-muted font-weight-normal">
                  {{ comment.created_on }}
                </span>
              </p>
              {{ comment.body | linebreaks }}
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="col-md-8 card mb-4  mt-3 ">
          <div class="card-body">
            {% if new_comment %}
            <div class="alert alert-success" role="alert">
              Your comment is awaiting moderation
            </div>
            {% else %}
            <h3>Leave a comment</h3>
            <form method="post" style="margin-top: 1.3em;">
              {{ comment_form.as_p }}
              {% csrf_token %}
              <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
            </form>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

    <!-- Footer -->
    <footer class="footer text-center">
        <div class="container">
            <div class="row">

                <!-- Footer Location -->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Location</h4>
                    <p class="lead mb-0">541/2 Nguyen Tri Phuong
                        <br>Ward 8, District 10, Ho Chi Minh city</p>
                </div>

                <!-- Footer Social Icons -->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Back to front</h4>
                    <a class="btn btn-outline-light btn-social mx-1" href="#">
                        <i class="fab fa-fw fa-facebook-f"></i>
                    </a>

                </div>

                <!-- Footer About Text -->
                <div class="col-lg-4">
                    <h4 class="text-uppercase mb-4">About abc Bookstore</h4>
                    <p class="lead mb-0">CK Bookstore is free for everyone who would like to share, sell books or just discuss and find some new books
                        <a href="http://tiki.vn">Start CK Bookstore</a>.</p>
                </div>

            </div>
        </div>
    </footer>

    <!-- Copyright Section -->
    <section class="copyright py-4 text-center text-white">
        <div class="container">
            <small>Copyright &copy; Your Website 2019</small>
        </div>
    </section>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-to-top d-lg-none position-fixed ">
        <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>

    <script type="text/javascript" src="{% static 'css_js' %}/js/jquery-1.10.2.min.js"></script>
    <script src="{% static 'css_js' %}/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="{% static 'css_js' %}/js/wow.min.js"></script>
    <script>
        new WOW().init();
    </script>
</body>

</html>

templates/inside/logout.html
<!doctype html> {% extends "base.html" %} {% block content %} {% load static %}
<div class="container">
    <h1> Logout </h1>
    <div class="container">
        <font color="red">{{result}}</font>
    </div>
</div>
{% endblock %}

templates/inside/registration.html
{% extends 'base.html' %} {% block content %}

<!-- Begin Service-section -->
<section id="services" class="services-section section-global-wrapper">
    <div class="container">
        <div class="row">
            {% if registered %}
            <h3> Thank you for your official registration ! - Your account has been saved</h3>
            {% else %}
            <h3> REGISTER HERE - BY FILLING THE FORM </h3>

            <table>
                <form method='POST' enctype="multipart/form-data">
                    {% csrf_token %} {% for field in user_form %}
                    <tr>
                        <td> {{field.label}} </td>
                        <td> {{field}} </td>
                    </tr>
                    {% endfor %} {% for field in profile_form %}
                    <tr>
                        <td> {{field.label}} </td>
                        <td> {{field}} </td>
                    </tr>
                    {% endfor %}

                    <tr>
                        <td colspan="2">
                            <input type="submit" class="btn btn-primary" value="Register">
                        </td>
                    </tr>

                </form>
            </table>
        </div>
        {% endif %}
    </div>
    </div>
</section>

{% endblock %}

templates/inside/signin.html
<!doctype html> {% extends "base.html" %} {% block content %} {% load static %}{% load socialaccount %}

<div class="container">
    <a>{{last}}</a>
    <h1> Login </h1>
    <form method="POST" action="{% url 'inside:signin' %}">
        <table>
            <tr>
                <td>
                    <lable for="username">Username: </lable>
                </td>
                <td><input type="text" name="username" placeholder="Enter Username">
                </td>
            </tr>

            <tr>
                <td>
                    <lable for="password">Password: </lable>
                </td>
                <td><input type="password" name="password" placeholder="Enter Password"></td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <input type="submit" class="btn btn-primary" value="Submit">
                </td>
            </tr>
        </table>
        {% csrf_token %}
    </form>
</div>
<div class="container">
    <font color="red">{{result}}</font>
</div>

<button class="btn btn-primary">
    <a href="{% url 'social:begin' 'facebook' %}">Login with Facebook</a>
</button>


<button class="btn btn-primary">
    <a href="{% provider_login_url 'google' %}">Login with Google</a>
</button> {% endblock %} {% load socialaccount %}

templates/inside/signup.html
{% load static %}


<div class='row'>
    <form method="post">
        {{form.as_p}} {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="submit">
    </form>
</div>

templates/inside/user_change_password.html
{% extends 'base.html' %} {% block content %}

<!-- Begin Service-section -->
<section id="services" class="services-section section-global-wrapper">
    <div class="container">
      <div class="container">
  <a>{{last}}</a>
  <h1> Password Changing </h1>
  <form method="POST" action="{% url 'inside:user_change_password' %}">
    <table>
 <form method="post">
      {% csrf_token %}
      {% for field in form %}
    <tr>
      <th>{{ field.label_tag }} </th>
        <td>
          <div class="form-group">
            {{ field }}
            {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </div>
        </td>
    </tr>
            {% endfor %}
    <tr>
      <td></td>
      <td><button  class="primary-btn" type="submit">Change Password</button></td>
  </tr>
</form>
</table>
</div>





</section>

{% endblock %}

templates/inside/user_detail.html
{% extends 'base.html' %} {% block content %}

<!-- Begin Service-section -->
<section id="services" class="services-section section-global-wrapper">
  <div class="section">
     <!-- container -->
     <div class="container">
         <!-- row -->
         <div class="row">

             <div class="col-md-2">
                 <div class="billing-details">

                 </div>
             </div>
             <div class="col-md-8">
                 <div class="billing-details">

                     {% if messages %}
                         {% for message in messages %}
                             <div class="alert alert-{{message.tags}}" role="alert">
                                 {{ message }}
                             </div>
                         {% endfor %}
                     {% endif %}

                     <table class="shopping-cart-table table">
                         <thead>
                         <tr>
                             <th>User Name</th>   <td> {{ user.username }}</td>
                         </tr>
                         <tr>
                             <th>First Name</th>   <td>{{ user.first_name }}</td>
                         </tr>

                         <tr>
                             <th>Last Name</th>   <td>{{ user.last_name }}</td>
                         </tr>
                         <tr>
                             <th>Email</th>   <td>{{ user.email }}</td>
                      


                         </thead>

                     </table>
                 </div>
        </div>
      </div>
    </div>
  </div>
  </section>



</section>

{% endblock %}

templates/inside/user_update.html
{% extends 'base.html' %} {% block content %}

<!-- Begin Service-section -->
<section id="services" class="services-section section-global-wrapper">
  <div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">

            <div class="col-md-2">
                <div class="billing-details">

                </div>
            </div>
            <div class="col-md-8">
                <div class="billing-details">

                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{message.tags}}" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <table>
                        <form method="post">
                            {% csrf_token %}

                            {% for field in form %}
                                <tr>
                                    <th>{{ field.label_tag }} </th>
                                    <td>
                                        <div class="form-group">
                                            {{ field }}
                                            {% if field.help_text %}
                                                <small style="color: grey">{{ field.help_text }}</small>
                                            {% endif %}
                                            {% for error in field.errors %}
                                                <p style="color: red">{{ error }}</p>
                                            {% endfor %}
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            <tr>
                                <td></td>
                                <td><button  class="primary-btn" type="submit">Update Profile</button></td>
                            </tr>
                        </form>
                    </table>



                </div>
            </div>






        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>

</section>

{% endblock %}