baithi/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from inside import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'inside/', include('inside.urls')),
    path(r'cart/', include('cart.urls')),
    path(r'social-auth/', include('social_django.urls', namespace="social")),
    path(r'orders/', include('orders.urls')),
    path(r'accounts/', include('allauth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inside/urls.py
from django.conf.urls import url
from inside import views
from django.urls import path

app_name = 'inside'

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'signin', views.signin, name = 'signin'),
    url(r'signup', views.signup, name = 'signup'),
    url(r'logout', views.user_logout, name = 'logout'),
    url(r'chi-tiet/(\d+)$', views.chiTiet,name='chi-tiet'),
    url(r'registered', views.Registration,name='registered'),
    path('user_change_password', views.user_change_password, name='user_change_password'),
    path('profile', views.user_profile, name='profile'),
    path('user_update', views.user_update, name='user_update'),
    
]

urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from inside import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'inside/', include('inside.urls')),
    path(r'cart/', include('cart.urls')),
    path(r'social-auth/', include('social_django.urls', namespace="social")),
    path(r'orders/', include('orders.urls')),
    path(r'accounts/', include('allauth.urls')),
    path(r'booking/', include('bookingsite.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>WELCOME TO BOOK STORE</title>

    <!-- Custom fonts for this theme -->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="assets/ico/favicon.ico">

    <!-- Theme CSS -->
    <link href="{% static 'css_js' %}/css/freelancer.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300">
    <link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
    <link href="http://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">WELCOME TO OUR BOOKSTORE</a>
            <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'inside:index' %}">About</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'inside:index' %}">Contact</a>
                    </li>
                    <li class="nav-item mx-0 mx-lg-1">
                        <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'inside:registered' %}">Register</a>
                    </li>

                          {% if user.is_authenticated %}
                          <li class="nav-item mx-0 mx-lg-1">
                            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'inside:logout' %}">Log out</a>
                          <li class="nav-item mx-0 mx-lg-1">
                            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'inside:profile' %}">Profile</a>
                          <li class="nav-item mx-0 mx-lg-1">
                            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'inside:user_update' %}">User Update</a>
                          <li class="nav-item mx-0 mx-lg-1">
                            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'inside:user_change_password' %}">Change Password</a>


                          {% else %}
                            <li class="nav-item mx-0 mx-lg-1">
                              <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'inside:signin' %}">Log in</a>

                          {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <!-- End Header -->

    <!-- Masthead -->
    <header class="masthead bg-primary text-white text-center">
        <div class="container d-flex align-items-center flex-column">

            <!-- Masthead Avatar Image -->
            <img class="masthead-avatar mb-5" src="img/avataaars.svg" alt="">

            <!-- Masthead Heading -->
            <h1 class="masthead-heading text-uppercase mb-0">CK BOOKSTORE</h1>

            <!-- Icon Divider -->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                </div>
                <div class="divider-custom-line"></div>
            </div>

            <!-- Masthead Subheading -->
            <p class="masthead-subheading font-weight-light mb-0">Book Sales - Book Share - Book Fun</p>

        </div>
    </header>

    <!-- Begin #services-section -->
    {% block content %} {% endblock %}
    <!-- End #services-section -->


    <!-- Footer -->
    <footer class="footer text-center">
        <div class="container">
            <div class="row">

                <!-- Footer Location -->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Location</h4>
                    <p class="lead mb-0">541/2 Nguyen Tri Phuong
                        <br>Ward 8, District 10, Ho Chi Minh city</p>
                </div>

                <!-- Footer Social Icons -->
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Back to front</h4>
                    <a class="btn btn-outline-light btn-social mx-1" href="#">
                        <i class="fab fa-fw fa-facebook-f"></i>
                    </a>
                </div>

                <!-- Footer About Text -->
                <div class="col-lg-4">
                    <h4 class="text-uppercase mb-4">About CK Bookstore</h4>
                    <p class="lead mb-0">CK Bookstore is free for everyone who would like to share, sell books or just discuss and find some new books
                        <a href="http://tiki.vn">Start CK Bookstore</a>.</p>
                </div>

            </div>
        </div>
    </footer>

    <!-- Copyright Section -->
    <section class="copyright py-4 text-center text-white">
        <div class="container">
            <small>Copyright &copy; Your Website 2019</small>
        </div>
    </section>

    <script type="text/javascript" src="{% static 'css_js' %}/js/jquery-1.10.2.min.js"></script>
    <script src="{% static 'css_js' %}/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="{% static 'css_js' %}/js/wow.min.js"></script>
    <script>
        new WOW().init();
    </script>

</body>

</html>